import base64

# Simple 100x100 Purple PNG for Logo
logo_b64 = "iVBORw0KGgoAAAANSUhEUgAAAGQAAABCkCAIAAAD/gAIDAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAiklEQVR4nO3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfzPgigABcO52dAAAAABJRU5ErkJggg=="

# Simple 400x200 Dark Grey PNG for Menu
menu_b64 = "iVBORw0KGgoAAAANSUhEUgAAAZAAAADICAYAAADGFbgLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA6SURBVHhe7cExAQAAAMKg9U9tCy8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAvwGueAABj4iXBAAAAABJRU5ErkJggg=="

with open("logo.png", "wb") as f:
    f.write(base64.b64decode(logo_b64))

with open("menu.png", "wb") as f:
    f.write(base64.b64decode(menu_b64))

print("Placeholder images created: logo.png, menu.png")